### ISSUE TITLE
Binance TP order issue

### ISSUE THREAD

**Issue by options2015** [donewiththedollar/directionalscalper#51]
I am running the binance_auto_hedge_maker strategy and the error below is constantly appearing in the console. Is this something that needs to be fixed or ignored?

```
An error occurred while creating the take-profit order: binance {"code":-2021,"msg":"Order would immediately trigger."}

Directional Scalper 2.0.6
Binance auto hedge strategy running
```

**Comment by donewiththedollar** [comment]
Needs to be resolved, binance does not like to play nice with post only orders so we are using market TP at the moment. Based on my analysis it seems the strategy runs smooth and profits but this is still something that needs to be re worked so the take profits are proper limits that are post onlys.
