### ISSUE TITLE
line 143 in load_config

### ISSUE THREAD

**Issue by eogh303** [donewiththedollar/directionalscalper#54]
line 143 in load_config
raise valueError(f{path} does not exist")
value error configs/configs/config.json

**Comment by donewiththedollar** [comment]
Hey! Try running like this to see if it works, with your config named config.json in configs folder.

``python3.11 multi_bot.py --exchange bybit --account_name account_1 --strategy bybit_mfirsi_trend_rotator --config config.json``

**Comment by eogh303** [comment]
raise ValueError(f"Configuration Error(s):\n{error_details}")

ValueError: Configuration Error(s):

('bot', 'shared_data_path') - Path does not point to a directory

**Comment by donewiththedollar** [comment]
That sounds like pydantic is trying to read your shared_data_path from your config.json and it's invalid; however the config is structured in such a way that it should ignore the shared data path in config.json when the dashboard is set to false (the default setting).

It seems setting your shared_data_path in the config.json to your actual project directory (like mine was /home/ubuntu/directionalscalper/) you can save the config and the bot should proceed from there.

However, I must look into why pydantic is not being cooperative here, it is almost sounding like a validator issue.
