### ISSUE TITLE
retcode 10006 "Too many visits"

### ISSUE THREAD

**Issue by ilaykim** [donewiththedollar/directionalscalper#57]
https://github.com/donewiththedollar/directionalscalper/blame/260c73f3904ca1982c9668bccc18cfc194a7ecc9/directionalscalper/core/exchange.py#L985C32-L985C32

maybe check for retcode 10006 and if so wait a second and retry for the win

An error occurred while fetching all open orders: bybit {"retCode":10006,"retMsg":"Too many visits","result":{},"retExtInfo":{},"time":1693924869139}

**Comment by donewiththedollar** [comment]
Problem solved  💯
