### ISSUE TITLE
  error     pip3.11 install -r requirements.txt 

### ISSUE THREAD

**Issue by qq020608** [donewiththedollar/directionalscalper#61]
os: 
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

i got this error with       pip3.11 install -r requirements.txt 

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement sqlite (from versions: none)
ERROR: No matching distribution found for sqlite

**Comment by donewiththedollar** [comment]
Removed sqlite requirement, problem solved :)
