### ISSUE TITLE
local api

### ISSUE THREAD

**Issue by ddkargas** [donewiththedollar/directionalscalper#70]
Can't undestand how can work api in local mode and not remote. 
How can generate in local directory json files to load from script?

Thanks Jim

**Comment by donewiththedollar** [comment]
I will update the readme with an explanation on how to run the API locally, but keep in mind it is a bit resource intensive as it uses multiprocessing.

For now, you can run the multiprocessing api by simply running it from the directionalscalper project folder like ``python3.11 api/multiprocessing_api.py`` for example (naming is off there for the file)
