### ISSUE TITLE
"retCode":10002,"retMsg":"invalid request, please check your server timestamp

### ISSUE THREAD

**Issue by LatifTadvi** [donewiththedollar/directionalscalper#77]
I am getting server timestamp error

**Comment by amit-sides** [comment]
have you checked your server timestamp (like it suggested in the error) ?

**Comment by LatifTadvi** [comment]
An error occurred while fetching symbols: bybit {"retCode":10002,"retMsg":"invalid request, please check your server timestamp or recv_window param. req_timestamp[1706469488669],server_timestamp[1706469486932],recv_window[5000]","result":{},"retExtInfo":{},"time":1706469486932}, retrying in 10 seconds...

**Comment by LatifTadvi** [comment]
This is resolved.
![image](https://github.com/donewiththedollar/directionalscalper/assets/120674062/fa13fc22-b9b0-4774-b32d-89408ccb79dc)
I just clicked on sync now and its working fine,
