### ISSUE TITLE
Streamlit run dashboard.py : FileNotFoundError: [Errno 2] No such file or directory: 'data/open_positions_data.json'

### ISSUE THREAD

**Issue by guntoken** [donewiththedollar/directionalscalper#89]
Hello,

I've followed the installation instructions precisely, but when I attempt to run streamlit run dashboard.py, I encounter a FileNotFoundError pointing to the absence of "data/open_positions_data.json".

Here's the exact error message:

"FileNotFoundError: [Errno 2] No such file or directory: 'data/open_positions_data.json'"

Could you please advise on why this file is missing and how I can resolve this issue? Is there an initial setup step I might have overlooked, or should this file be generated automatically during the process?

Thank you for your assistance

**Comment by donewiththedollar** [comment]
Hey! Which strategy are you using? I added extra logging and exception handling to the bybit strategies and tested the dashboard and it actually works fine without this error.

**Comment by clebersonjf83** [comment]
![Screenshot_20240620-204219](https://github.com/donewiththedollar/directionalscalper/assets/22937874/882c346c-86ec-4da9-852b-f0f444f2fdb1)

The same error also happens to me, I'm using bybit with the qsgridob strategy. How to solve it, I'm very new to programming...

Note. Sorry for my English, I use the translator.
